# Nom public du workflow
name: Application Pipeline

# Déclencheur : s'active à chaque push sur le dépôt
on: [push]

jobs:
  # Déclaration du job unique
  validate-code:
    # Spécification de l'agent d'écoute (Ubuntu version stable la plus récente)
    runs-on: ubuntu-latest
    
    steps:
      # Étape 1 : Cloner le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Installer les dépendances Node.js
      - name: Install dependencies
        run: npm install

      # Étape 3 : Lancer la suite de tests
      - name: Run tests
        run: npm test
      # Optionnel : pour publier les résultats des tests sur GitHub
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() # S'exécute même si les tests échouent
        with:
          report_paths: 'junit.xml'
      - name: "Verification Securite et Masquage"
        env:
          CURRENT_ENV: ${{ vars.APP_ENVIRONMENT }}
          SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        run: |
          echo "L'environnement actuel est : $CURRENT_ENV"
          # La clé secrète sera automatiquement masquée par GitHub si elle est bien configurée
          echo "Tentative d'affichage de la cle secrete : $SECRET_KEY"    